# Generated by Django 4.2.1 on 2023-05-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_user_is_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
