# Generated by Django 4.2.1 on 2023-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_rename_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_ip',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
