# Generated by Django 4.2.1 on 2023-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_user_user_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_try_2',
            field=models.CharField(default=3, max_length=2),
        ),
    ]
