# Generated by Django 4.2.1 on 2023-05-09 08:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number must be 11 digits.', regex='^\\d{11}')]),
        ),
    ]
